name: "preview builder 👀"
on:
  pull_request:
  workflow_dispatch:

env:
  CI: true
  HUSKY: 0
  NUXT_SITE_ENV: staging # used for NuxtSEO to disable things like indexing on staging

jobs:
  build_and_preview:
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    environment: preview
    runs-on: ubuntu-latest
    outputs:
      output_urls: "${{ steps.preview_deploy.outputs.urls }}"
    steps:
      - uses: actions/checkout@v4 # v4

      - uses: oven-sh/setup-bun@v1

      - name: "Install dependencies"
        run: bun install --production --frozen-lockfile

      - name: "Deploy target: staging"
        run: bun run build

      - name: "Deploy preview"
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_SDK_DOCS_STAGING }}"
          projectId: zksync-sdk-docs-staging
