name: "deploy staging 🏗️"
on:
  push:
    branches: [staging]

env:
  CI: true
  HUSKY: 0
  NUXT_SITE_ENV: staging # used for NuxtSEO to disable things like indexing on staging

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  build_and_deploy:
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
    if: ${{ github.event.repository.full_name == github.repository }}
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4
        with:
          ref: "${{ github.event.inputs.ref }}"

      - uses: oven-sh/setup-bun@v1

      - name: "Install dependencies"
        run: bun install --production --frozen-lockfile
      - name: "Deploy target: staging"
        run: bun run build

      - uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_SDK_DOCS_STAGING }}"
          projectId: zksync-sdk-docs-staging
          channelId: live
